server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:1234567localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
        hostname: localhost
        prefer-ip-address: true



spring:
  application:
    name: ms-gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ahcc-cursos
              uri: lb://ahcc-cursos
              predicates:
                - Path=/Cursos/**
            - id: sm-marca
              uri: lb://sm-marca
              predicates:
                - Path=/marca/
                  
eureka-client:
  service-url:
    defaultZone: http://root:1234567@localhost:8761/eureka
