server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # ⚠️ SIN credenciales
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: ms-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ahcc-cursos
          uri: lb://ahcc-cursos
          predicates:
            - Path=/Cursos/**
        - id: sm-marca
          uri: lb://sm-marca
          predicates:
            - Path=/marca/**