spring:
  application:
    name: ahcc-registrey-server
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:1234567@localhost:7070


  security:
    user:
      name: root
      password: 1234567
